# Generated by Django 3.2.25 on 2024-08-25 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان گواهی نامه')),
                ('image', models.ImageField(upload_to='images/certificates', verbose_name='تصویر گواهی نامه')),
                ('address', models.CharField(max_length=400, verbose_name='آدرس تصویر')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / غیرفعال')),
            ],
            options={
                'verbose_name': 'گواهی نامه',
                'verbose_name_plural': 'گواهی نامه ها',
            },
        ),
    ]
