# Generated by Django 3.2.25 on 2024-08-25 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_module', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='address',
        ),
    ]
