# Generated by Django 3.2.25 on 2024-08-26 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان')),
                ('short_des_one', models.CharField(max_length=300, verbose_name='توضیحات کوتاه اول')),
                ('short_des_two', models.CharField(max_length=300, verbose_name='توضیحات کوتاه دوم')),
                ('location', models.CharField(max_length=100, verbose_name='موقعیت')),
                ('email', models.EmailField(max_length=254, verbose_name='آدرس ایمیل')),
                ('phone', models.CharField(max_length=11, verbose_name='شماره موبایل')),
                ('is_active', models.BooleanField(default=False, help_text='فقط یک فرم فعال برای اطلاعات تماس مجاز می باشد', verbose_name='فعال / غیرفعال')),
            ],
            options={
                'verbose_name': 'اطلاعات تماس با من',
                'verbose_name_plural': 'لیست اطلاعات تماس با من',
            },
        ),
    ]
