# Generated by Django 3.2.25 on 2024-08-25 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='نام و نام خانوادگی')),
                ('img_profile', models.ImageField(upload_to='images/profile', verbose_name='تصویر پروفایل')),
                ('bio_one', models.CharField(max_length=200, verbose_name='بیوگرافی اول')),
                ('bio_two', models.CharField(max_length=200, verbose_name='بیوگرافی دوم')),
                ('resume', models.FileField(upload_to='files/resume', verbose_name='فایل رزومه')),
                ('github', models.URLField(verbose_name='لینک گیت هاب')),
                ('instagram', models.CharField(max_length=200, verbose_name='آی دی اینستاگرام')),
                ('telegram', models.CharField(max_length=200, verbose_name='آی دی تلگرام')),
                ('whatsapp', models.CharField(max_length=200, verbose_name='شماره واتس آپ')),
                ('is_main_profile', models.BooleanField(db_index=True, default=False, help_text='فقط یک پروفایل مجاز به استفاده می باشد', verbose_name='پروفایل اصلی')),
            ],
            options={
                'verbose_name': 'پروفایل',
                'verbose_name_plural': 'پروفایل ها',
            },
        ),
    ]
