# Generated by Django 3.2.25 on 2024-09-05 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='priority',
            field=models.IntegerField(default=1, verbose_name='اولویت بر اساس عدد'),
            preserve_default=False,
        ),
    ]
